# Generated by Django 3.2.8 on 2021-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='video_title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
